#! /bin/sh

zebraconf() {
	echo "password secret"
	echo "enable password secret"
	echo "log file /tmp/vnet$1-zebra.log"
	echo "ip forwarding"

	if test ${dest} -eq $1
	then
		echo "interface lo"
		echo " ip address 192.168.1.1/16"
	fi
}

bgpdconf() {
	local i

	echo "password secret"
	echo "enable password secret"
	echo "log file /tmp/vnet$1-bgpd.log"
	echo "debug bgp updates"

	as=`expr 65000 + $1`
	echo "router bgp ${as}"
	echo " bgp router-id 10.0.0.$1"
	echo " bgp graceful-restart"

	if test ${dest} -eq $1
	then
		echo " network 192.168.0.0/16"
		echo " neighbor 10.0.0.1 remote-as 65001"
		echo " neighbor 10.0.0.2 remote-as 65002"
		echo " neighbor 10.0.0.2 route-map backup out"
		echo "route-map backup permit 10"
		printf " set as-path prepend"
		for i in `seq $n`
		do
			printf " ${as}"
		done
		echo
		return
	fi

	for i in `seq $n`
	do
		if test $i -ne $1
		then
			echo " neighbor 10.0.0.$i remote-as" `expr 65000 + $i`
			echo " neighbor 10.0.0.$i next-hop-self"
		fi
	done
	if test 2 -ge $1
	then
	        echo " neighbor 10.0.0.${dest} remote-as" `expr 65000 + ${dest}`
	fi
}

monitor() {
	local i

	files=
	for i in `seq $n`
	do
		o=/tmp/vnet$i-rtmon.txt
		files="$files $o"
		ip monitor file /tmp/vnet$i-rtmon.log >$o
	done
}

converge() {
	echo Waiting for convergence.
	converged=0
	until test $converged -eq $n
	do
		sleep 2
		monitor
		$collect $files >/tmp/vnet-fibs.txt
		$detect /tmp/vnet-fibs.txt >/tmp/vnet-converged.txt
		converged=`tail -n 1 /tmp/vnet-converged.txt | cut -d, -f2`
	done
}

if test $# != 2 || test $1 -lt 2
then
	echo Usage: $0 SIZE COUNT
	echo SIZE must be at least 2.
	exit 1
fi
n=$1
count=$2
dest=`expr $n + 1`
vnet=`dirname $0`/vnet
collect=`dirname $0`/collect-fibs.py
detect=`dirname $0`/detect-convergence.py

$vnet create ${dest}
for i in `seq ${dest}`
do
	echo Configuring router $i.
	zebraconf $i >/tmp/vnet$i-zebra.conf
	bgpdconf $i >/tmp/vnet$i-bgpd.conf

	echo Starting router $i.
	ssh -f 10.0.0.$i rtmon -4 file /tmp/vnet$i-rtmon.log route
	ssh 10.0.0.$i /usr/lib/quagga/zebra -d -f /tmp/vnet$i-zebra.conf -i /tmp/vnet$i-zebra.pid
	ssh 10.0.0.$i /usr/lib/quagga/bgpd -d -f /tmp/vnet$i-bgpd.conf -i /tmp/vnet$i-bgpd.pid
done

converge

for i in `seq ${count}`
do
	echo Restart $i.
	pkill -f "vnet1-(zebra|bgpd)"
	ssh 10.0.0.1 /usr/lib/quagga/zebra -d -f /tmp/vnet1-zebra.conf -i /tmp/vnet1-zebra.pid
	ssh 10.0.0.1 /usr/lib/quagga/bgpd -d -f /tmp/vnet1-bgpd.conf -i /tmp/vnet1-bgpd.pid
	converge
done

$vnet destroy

echo Cleaning up routers.
pkill -f vnet
