#! /bin/sh

cat >data/converged.gnuplot <<END
set terminal postscript enhanced color
set output '| ps2pdf - data/converged.pdf'
set datafile separator ','
set title 'Converged Routers'
set xlabel 'Time (seconds)'
set ylabel '# Routers'
END

prefix='plot '
for i in data/*/converged.log
do
	printf "${prefix}'$i' with steps notitle" >>data/converged.gnuplot
	prefix=", \\\\\\n  "
done

gnuplot data/converged.gnuplot
