#! /bin/sh

mkdir -p data
for dir in run-*
do
	start=`cat "$dir"/experiment/start`
	stop=`cat "$dir"/experiment/stop`
	tshark -r "$dir"/monitor/bgp.pcap -R "bgp.type!=4 && frame.time_epoch>=$start && frame.time_epoch<$stop" -T fields -e frame.time_delta_displayed 2>/dev/null |
	awk '{t += $1} END {print t}'
done | sort -n > data/convergence
