#! /bin/sh

NODES=`cat bgp/clique`
mkdir -p data
for dir in run-*
do
	start=`cat "$dir"/experiment/start`
	stop=`cat "$dir"/experiment/stop`
	tshark -r "$dir"/monitor/bgp.pcap -R "frame.time_epoch>=$start && frame.time_epoch<$stop && (bgp.nlri_prefix==10.0.0.1 || bgp.withdrawn_prefix==10.0.0.1)" -T fields -e ip.dst 2>/dev/null | sort | uniq -c | awk '{print $1}'
done | sort -n >data/updates
