#! /bin/sh

birdconf() {
	local i peers

	echo log \"`pwd`/tmp/nodes/bird$1.log\" all\;
	echo debug protocols all\;
	echo router id 192.168.1.$1\;

	echo protocol device {
	echo }

	echo protocol kernel {
	echo "" export all\;
	echo }

	as=`expr 65000 + $1`
	if test $1 -le 2
	then
		peers=`seq $dest`
	else
		peers=`seq $nodes`
	fi
	for i in $peers
	do
		if test $i -ne $1
		then
			echo protocol bgp bgp$i {
			echo "" local as $as\;
			echo "" neighbor 192.168.1.$i as `expr 65000 + $i`\;
			echo "" next hop self\;
			echo "" export all\;
			echo }
		fi
	done
}

startscript() {
	local i
	echo mkdir -p `pwd`/tmp/nodes
	for i in `seq $nodes`
	do
		echo ip netns exec vbgp$i start-stop-daemon -p `pwd`/tmp/nodes/bird$i.pid -b -m -S -a `which bird` -- -c `pwd`/config/nodes/bird$i.conf -d -s `pwd`/tmp/nodes/bird$i.ctl
	done
}

stopscript() {
	for i in `seq $nodes`
	do
		echo start-stop-daemon -p `pwd`/tmp/nodes/bird$i.pid -K
	done
}

nodes=`cat config/network/nodes`
dest=`expr $nodes + 1`

mkdir -p config/nodes
for i in `seq $nodes`
do
	birdconf $i >config/nodes/bird$i.conf
done
startscript >config/nodes/start
stopscript >config/nodes/stop
chmod a+x config/nodes/start config/nodes/stop
