#! /bin/sh

zebraconf() {
	echo "password secret"
	echo "enable password secret"
	echo "log file ${dir}/$1/quagga/zebra.log"
	echo "ip forwarding"
}

bgpdconf() {
	local i

	echo "password secret"
	echo "enable password secret"
	echo "log file ${dir}/$1/quagga/bgpd.log"
	echo "debug bgp updates"

	as=`expr 65000 + $1`
	echo "router bgp ${as}"
	echo " bgp router-id 192.168.1.$1"
	echo " bgp graceful-restart"

	for i in `seq $n`
	do
		if test $i -ne $1
		then
			echo " neighbor 192.168.1.$i remote-as" `expr 65000 + $i`
			echo " neighbor 192.168.1.$i next-hop-self"
		fi
	done
	if test 2 -ge $1
	then
	        echo " neighbor 192.168.1.${dest} remote-as" `expr 65000 + ${dest}`
		echo " neighbor 192.168.1.${dest} next-hop-self"
	fi
}

startscript() {
	echo mkdir -p ${dir}/$1/quagga
	echo chown quagga:quagga ${dir}/$1/quagga
	echo /usr/lib/quagga/zebra -d -f ${dir}/$1/zebra.conf -i ${dir}/$1/quagga/zebra.pid
	echo /usr/lib/quagga/bgpd -d -f ${dir}/$1/bgpd.conf -i ${dir}/$1/quagga/bgpd.pid
}

stopscript() {
	echo kill \`cat ${dir}/$1/quagga/zebra.pid ${dir}/$1/quagga/bgpd.pid\`
}

if test $# -ne 1
then
	echo Usage: $0 SIZE
	exit 1
fi

n=$1
dest=`expr $n + 1`
dir=`pwd`/nodes
mkdir -p ${dir}
for i in `seq $n`
do
	echo Configuring router $i.
	mkdir ${dir}/$i
	zebraconf $i >${dir}/$i/zebra.conf
	bgpdconf $i >${dir}/$i/bgpd.conf
	startscript $i >${dir}/$i/start
	stopscript $i >${dir}/$i/stop
done
