#! /bin/sh

: ${NODES:=1}

mkdir -p network
echo $NODES >network/nodes

cat >network/start <<END
#! /bin/sh

ip link add nodes type bridge
ip link set nodes up

for i in \`seq $NODES\`
do
	ip netns add node\$i
	ip link add node\$i type veth peer name nodeeth\$i
	ip link set node\$i master nodes
	ip link set node\$i up
	ip link set nodeeth\$i netns node\$i name eth0
	ip netns exec node\$i ip address add 192.168.1.\$i/24 dev eth0
	ip netns exec node\$i ip link set eth0 up
	ip netns exec node\$i ip link set lo up
done
END
chmod a+x network/start

cat >network/stop <<END
#! /bin/sh

for i in \`seq $NODES\`
do
	ip link set node\$i down
	ip link delete node\$i
	ip netns delete node\$i
done

ip link set nodes down
ip link delete nodes
END
chmod a+x network/stop
