#! /bin/sh

if test $# -ne 1
then
	echo Usage: $0 SIZE
	exit 1
fi

nodes=$1
dest=`expr $nodes + 1`

startscript() {
	local i
	echo brctl addbr vbgp
	echo ip link set vbgp up
	for i in `seq $dest`
	do
		echo ip netns add vbgp$i
		echo ip link add name vbgp$i type veth peer name vbgpeth$i
		echo ip link set vbgpeth$i netns vbgp$i name eth0
		echo ip netns exec vbgp$i ip address add 192.168.1.$i/24 dev eth0
		echo ip netns exec vbgp$i ip link set eth0 up
		echo ip netns exec vbgp$i ip link set lo up
		echo ip link set vbgp$i up
		echo brctl addif vbgp vbgp$i
	done
}

stopscript() {
	local i
	for i in `seq $dest`
	do
		echo ip link set vbgp$i down
		echo ip link del vbgp$i
		echo ip netns del vbgp$i
	done
	echo ip link set vbgp down
	echo brctl delbr vbgp
}

mkdir -p config/network
echo $nodes >config/network/nodes
startscript >config/network/start
stopscript >config/network/stop
chmod a+x config/network/start config/network/stop
